spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: springcloud-config-lgz-dev
---
spring:
  profiles: test
  application:
    name: springcloud-config-lgz-test
#保存格式为 utf-8